In [ ]:
pip install layer-sdk

     |████████████████████████████████| 26.6 MB 77 kB/s 
     |████████████████████████████████| 159 kB 60.7 MB/s 
     |████████████████████████████████| 97 kB 6.5 MB/s 
     |████████████████████████████████| 2.6 MB 51.7 MB/s 
     |████████████████████████████████| 2.5 MB 45.7 MB/s 
     |████████████████████████████████| 1.3 MB 60.9 MB/s 
     |████████████████████████████████| 636 kB 54.6 MB/s 
     |████████████████████████████████| 294 kB 62.4 MB/s 
     |████████████████████████████████| 131 kB 68.9 MB/s 
     |████████████████████████████████| 14.6 MB 88 kB/s 
     |████████████████████████████████| 209 kB 40.8 MB/s 
     |████████████████████████████████| 23.6 MB 96 kB/s 
     |████████████████████████████████| 212.4 MB 71 kB/s 
     |████████████████████████████████| 370 kB 73.2 MB/s 
     |████████████████████████████████| 3.0 MB 44.9 MB/s 
     |████████████████████████████████| 63 kB 2.2 MB/s 
     |████████████████████████████████| 142 kB 58.9 MB/s 
     |███████████████

In [ ]:
pip install -U ipython

     |████████████████████████████████| 786 kB 39.8 MB/s 
  Attempting uninstall: ipython
    Found existing installation: ipython 5.5.0
    Uninstalling ipython-5.5.0:
      Successfully uninstalled ipython-5.5.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-console 5.2.0 requires prompt-toolkit<2.0.0,>=1.0.0, but you have prompt-toolkit 3.0.20 which is incompatible.
google-colab 1.0.0 requires ipython~=5.5.0, but you have ipython 7.26.0 which is incompatible.


In [ ]:
import layer

In [ ]:
layer.login()

Please open the following link in your web browser. Once logged in, copy the code and paste it here.
https://auth.beta.layer.co/authorize?response_type=code&code_challenge=nPHRp-C1JplMLZlgLu_AIlilP0lEzVk2T_HoDJiMIec&code_challenge_method=S256&client_id=tvp1Wo8acTt4z46c7MbUB3Rg5MqfmqkN&redirect_uri=https://beta.layer.co/oauth/code&scope=offline_access&audience=https://beta.layer.co
Code: -y4X5JT2EZwPRNTC
Successfully logged into https://beta.layer.co


In [129]:
from sklearn.model_selection import train_test_split
import zipfile
import wget
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, Dense,GlobalAveragePooling1D,Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np
import keras

In [ ]:
df = layer.get_dataset("spam_messages")

In [ ]:
df = df.to_pandas()

In [ ]:
df.head()

label  id  punct                                            message  length
0   ham   0      9  Go until jurong point, crazy.. Available only ...     111
1   ham   1      6                      Ok lar... Joking wif u oni...      29
2  spam   2      6  Free entry in 2 a wkly comp to win FA Cup fina...     155
3   ham   3      6  U dun say so early hor... U c already then say...      49
4   ham   4      2  Nah I don't think he goes to usf, he lives aro...      61

In [ ]:
from typing import Any
from layer import Dataset
from sklearn.preprocessing import LabelEncoder


labelencoder = LabelEncoder()
df = df.assign(is_spam = labelencoder.fit_transform(df["label"]))
df.drop(columns=["label"], inplace=True)


In [ ]:
df.tail()

id  punct  ... length  is_spam
5567  5567      8  ...    160        1
5568  5568      1  ...     36        0
5569  5569      7  ...     57        0
5570  5570      1  ...    125        0
5571  5571      1  ...     26        0

[5 rows x 5 columns]

In [ ]:
pip install wget

In [ ]:
X = df['message']
y = df['is_spam']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.15,
        random_state=0
    )

In [ ]:
X_test.head()

4456    Storming msg: Wen u lift d phne, u say "HELLO"...
690     <Forwarded from 448712404000>Please CALL 08712...
944     And also I've sorta blown him off a couple tim...
3768                  Sir Goodmorning, Once free call me.
1189    All will come alive.better correct any good lo...
Name: message, dtype: object

In [ ]:
vocab_size = 1000
oov_token = "<OOV>"

In [ ]:
tokenizer = Tokenizer(num_words=vocab_size, oov_token=oov_token)
tokenizer.fit_on_texts(X_train)

X_train_sequences = tokenizer.texts_to_sequences(X_train)
X_test_sequences = tokenizer.texts_to_sequences(X_test)

In [ ]:
word_index = tokenizer.word_index



In [ ]:
# word_index

In [ ]:
url = 'http://nlp.stanford.edu/data/glove.6B.zip'
filename = wget.download(url)

In [ ]:
with zipfile.ZipFile(filename, 'r') as zip_ref:
  zip_ref.extractall('glove')

In [ ]:
max_length = 100
padding_type = "post"
truncation_type = "post"

X_train_padded = pad_sequences(X_train_sequences, maxlen=max_length, padding=padding_type,
                                   truncating=truncation_type)
X_test_padded = pad_sequences(X_test_sequences, maxlen=max_length,
                                  padding=padding_type, truncating=truncation_type)

In [ ]:
embeddings_index = {}
f = open('glove/glove.6B.100d.txt')
for line in f:
  values = line.split()
  word = values[0]
  coefs = np.asarray(values[1:], dtype='float32')
  embeddings_index[word] = coefs
f.close()

embedding_matrix = np.zeros((len(word_index) + 1, max_length))

In [ ]:
embeddings_index['forever']

array([-0.02962  ,  0.02501  ,  0.55628  , -0.40107  ,  0.31203  ,
        0.72898  , -0.16204  ,  0.0308   ,  0.35242  , -0.60221  ,
       -0.030428 ,  0.86107  ,  0.70624  , -0.14869  , -0.28837  ,
       -0.6763   ,  0.8031   ,  0.73101  , -0.080868 ,  0.35766  ,
        0.22465  ,  0.36487  ,  0.024097 , -0.0072124,  0.45343  ,
        0.85817  , -0.21828  , -0.59258  ,  1.0031   ,  0.0063343,
        0.51643  ,  0.24284  , -0.13779  ,  0.046686 , -0.30697  ,
       -0.037773 , -0.23124  , -0.73011  , -0.22249  , -1.1748   ,
        0.302    ,  0.085231 ,  0.17523  ,  0.028652 , -0.31338  ,
       -0.23467  ,  0.40314  ,  0.92388  , -0.24224  , -1.385    ,
        0.015852 , -0.49981  ,  0.13854  ,  1.1617   ,  0.35233  ,
       -1.5063   ,  0.28455  ,  0.67725  ,  0.44386  ,  0.21196  ,
       -0.13162  ,  1.1688   , -0.74866  , -0.82651  ,  0.7592   ,
        0.49249  ,  0.78703  ,  0.43928  , -0.063966 , -0.55001  ,
        0.4577   , -0.1529   ,  0.058072 ,  0.14943  ,  0.1082

In [ ]:
for word, i in word_index.items():
  embedding_vector = embeddings_index.get(word)
  if embedding_vector is not None:
    # words not found in embedding index will be all-zeros.
    embedding_matrix[i] = embedding_vector
            
            

In [ ]:
embedding_layer = Embedding(len(word_index) + 1,
                                max_length,
                                weights=[embedding_matrix],
                                input_length=max_length,
                                trainable=False)

In [ ]:
len(word_index) + 1

8327

In [ ]:
# word_index

In [130]:
word_embedding_model = Sequential([
        embedding_layer,
        Dropout(0.2),
        GlobalAveragePooling1D(),
        Dropout(0.2),
        Dense(1, activation='sigmoid')
    ])


word_embedding_model.compile(optimizer='adam',
              loss=keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=[keras.metrics.BinaryAccuracy()])
callbacks = [
        EarlyStopping(patience=2),
    ]
num_epochs = 600
word_embedding_model.fit(X_train_padded, y_train, epochs=num_epochs, validation_data=(X_test_padded, y_test),
                        callbacks=callbacks)

loss, accuracy = word_embedding_model.evaluate(X_train_padded, y_train, verbose=1)



Epoch 1/600


/usr/local/lib/python3.7/dist-packages/keras/backend.py:4994: UserWarning: "`binary_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  '"`binary_crossentropy` received `from_logits=True`, but the `output`'


148/148 [==============================] - 1s 6ms/step - loss: 0.6074 - binary_accuracy: 0.8541 - val_loss: 0.5489 - val_binary_accuracy: 0.8636
Epoch 2/600
148/148 [==============================] - 1s 5ms/step - loss: 0.5202 - binary_accuracy: 0.8663 - val_loss: 0.4936 - val_binary_accuracy: 0.8636
Epoch 3/600
148/148 [==============================] - 1s 5ms/step - loss: 0.4813 - binary_accuracy: 0.8663 - val_loss: 0.4647 - val_binary_accuracy: 0.8636
Epoch 4/600
148/148 [==============================] - 1s 5ms/step - loss: 0.4565 - binary_accuracy: 0.8663 - val_loss: 0.4449 - val_binary_accuracy: 0.8636
Epoch 5/600
148/148 [==============================] - 1s 5ms/step - loss: 0.4393 - binary_accuracy: 0.8663 - val_loss: 0.4291 - val_binary_accuracy: 0.8636
Epoch 6/600
148/148 [==============================] - 1s 5ms/step - loss: 0.4245 - binary_accuracy: 0.8663 - val_loss: 0.4148 - val_binary_accuracy: 0.8636
Epoch 7/600
148/148 [==============================] - 1s 5ms/step - l

In [131]:
X_test_padded[0]

array([  1, 130, 517,   7,   1, 142,   1,   7, 150, 268,  28,   7, 681,
         1,  10, 142, 330,   1,  16, 268, 134, 142, 269,  16,   5, 367,
       141,   8,   7, 681, 124,  10, 305, 367,   1, 268,  95,  10, 142,
         1, 759,   1, 124,   1,   1,   1,  77,  29,   1, 142, 269,  16,
         5, 318, 376,  26, 211,   1, 368, 559, 559, 142,  97,   2, 368,
         1, 172,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=int32)

In [132]:
prediction = word_embedding_model.predict(X_test_padded[513])

In [134]:
prediction[0]

array([1.], dtype=float32)

In [135]:
if prediction[0][0]>0.5:
  print("Is spam")
else:
   print("Is not Spam")

Is spam


# Using the Layer generated  model in a notebook


In [136]:
layer_model = layer.get_model("glove_word_embedding_model")


In [137]:
print(layer_model.parameters)

{}


In [138]:
print(layer_model.metrics)

{'Training Loss': [(1629990168173, 0.09136352688074112)], 'Training Accuracy': [(1629990168163, 0.9679054021835327)], 'Testing Loss': [(1629990168266, 0.09355905652046204)], 'Testing Accuracy': [(1629990168253, 0.9617224931716919)]}


In [139]:
trained_classifier = layer_model.get_train()
trained_classifier

In [140]:
np.array(y_test)[513]

1

In [149]:
test_message =  np.expand_dims(X_test_padded[513], axis=0)

second_prediction = trained_classifier.predict(test_message)

In [150]:
second_prediction

array([[0.92767197]], dtype=float32)

In [151]:
if second_prediction[0][0]>0.5:
  print("Is spam")
else:
   print("Is not Spam")

Is spam


In [154]:
!curl --header "Content-Type: application/json; format=pandas-records" \
  --request POST \
  --data '[[197,  40,  22, 309,   3, 205,   7, 560, 293, 357,  21,   4,  18, 184,   5,   1, 145, 256,  17,   1,  49, 671, 325, 118,   1,   1,66,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,0,   0,   0,   0,   0,   0,   0,   0,   0]]' \
https://46629a05-66e8-4180-8493-b650bb3acc8d.inferences.beta.layer.co/invocations

[{"0": 0.9276719093322754}]

In [159]:
np.array(y_test)[50]

0

In [160]:
X_test_padded[50]

array([  1,  50,  22,   4, 168,  43,  10,  33,   1,   4,   5, 126,  64,
         1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=int32)

In [158]:
!curl --header "Content-Type: application/json; format=pandas-records" \
  --request POST \
  --data '[ [ 1,  50,  22,   4, 168,  43,  10,  33,   1,   4,   5, 126,  64,1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,0,   0,   0,   0,   0,   0,   0,   0,   0]]' \
https://46629a05-66e8-4180-8493-b650bb3acc8d.inferences.beta.layer.co/invocations

[{"0": 0.007864177227020264}]